using Fu.Framework;
using System.Runtime.CompilerServices;

namespace FlightReLive.UI
{
    public class FlightReLiveIcons : FuIcons
    {

        protected static string _CameraSettings = "\uE065";
        public static string CameraSettings { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CameraSettings; }
        protected static string _HeightMap = "\uE066";
        public static string HeightMap { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _HeightMap; }
        protected static string _GoogleMaps = "\uE067";
        public static string OpenStreetMap { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _GoogleMaps; }
        protected static string _VideoFile = "\uE068";
        public static string VideoFile { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _VideoFile; }
        protected static string _VideoPlayer = "\uE069";
        public static string VideoPlayer { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _VideoPlayer; }
        protected static string _Charts = "\uE06A";
        public static string Charts { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Charts; }
        protected static string _View3D = "\uE06B";
        public static string View3D { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _View3D; }
        protected static string _Aperture = "\uE06C";
        public static string Aperture { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Aperture; }
        protected static string _ISO = "\uE06D";
        public static string ISO { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ISO; }
        protected static string _Exposure = "\uE06E";
        public static string Exposure { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Exposure; }
        protected static string _ShutterSpeed = "\uE06F";
        public static string ShutterSpeed { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ShutterSpeed; }
        protected static string _DigitalZoom = "\uE070";
        public static string DigitalZoom { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _DigitalZoom; }
        protected static string _AltitudeRelative = "\uE071";
        public static string AltitudeRelative { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _AltitudeRelative; }
        protected static string _GPSPosition = "\uE072";
        public static string GPSPosition { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _GPSPosition; }
        protected static string _Speed = "\uE073";
        public static string Speed { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Speed; }
        protected static string _AltitudeAbsolute = "\uE074";
        public static string AltitudeAbsolute { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _AltitudeAbsolute; }
        protected static string _Drone = "\uE075";
        public static string Drone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Drone; }
        protected static string _GPSMarker = "\uE076";
        public static string GPSMarker { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _GPSMarker; }
        protected static string _Resolution = "\uE077";
        public static string Resolution { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Resolution; }
        protected static string _Framerate = "\uE078";
        public static string Framerate { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Framerate; }
        protected static string _Duration = "\uE079";
        public static string Duration { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Duration; }
        protected static string _Camera = "\uE07A";
        public static string Camera { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Camera; }
        protected static string _Path = "\uE07B";
        public static string Path { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Path; }
        protected static string _Preferences = "\uE07C";
        public static string Preferences { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Preferences; }
        protected static string _Inspector = "\uE07D";
        public static string Inspector { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Inspector; }
        protected static string _Check = "\uE07E";
        public static string Check { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Check; }
        protected static string _Warning = "\uE07F";
        public static string Warning { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Warning; }
        protected static string _Duplicate = "\uE080";
        public static string Duplicate { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Duplicate; }
        protected static string _Quit = "\uE081";
        public static string Quit { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Quit; }
        protected static string _About = "\uE082";
        public static string About { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _About; }
        protected static string _PostProcess = "\uE083";
        public static string PostProcess { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _PostProcess; }
        protected static string _POV = "\uE084";
        public static string POV { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _POV; }
        protected static string _Undo = "\uE085";
        public static string Undo { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Undo; }
        protected static string _Compass = "\uE086";
        public static string Compass { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Compass; }
        protected static string _Play = "\uE087";
        public static string Play { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Play; }
        protected static string _Pause = "\uE088";
        public static string Pause { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Pause; }
        protected static string _Backward = "\uE089";
        public static string Backward { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Backward; }
        protected static string _Forward = "\uE08A";
        public static string Forward { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Forward; }
        protected static string _BackwardStep = "\uE08B";
        public static string BackwardStep { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _BackwardStep; }
        protected static string _ForwardStep = "\uE08C";
        public static string ForwardStep { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ForwardStep; }
        protected static string _Unload = "\uE08D";
        public static string Unload { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Unload; }
        protected static string _SpeedUltraSlow = "\uE08E";
        public static string SpeedUltraSlow { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SpeedUltraSlow; }
        protected static string _SpeedSlow = "\uE08F";
        public static string SpeedSlow { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SpeedSlow; }
        protected static string _SpeedNormal = "\uE090";
        public static string SpeedNormal { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SpeedNormal; }
        protected static string _SpeedFast = "\uE091";
        public static string SpeedFast { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SpeedFast; }
        protected static string _SpeedUltraFast = "\uE092";
        public static string SpeedUltraFast { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SpeedUltraFast; }
        protected static string _Share = "\uE093";
        public static string Share { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Share; }
        protected static string _Import = "\uE094";
        public static string Import { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Import; }
        protected static string _SunClouds = "\uE095";
        public static string SunClouds { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SunClouds; }
        protected static string _Sunrise = "\uE096";
        public static string Sunrise { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Sunrise; }
        protected static string _Sunset = "\uE097";
        public static string Sunset { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Sunset; }
        protected static string _Globe = "\uE098";
        public static string Globe { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Globe; }
        protected static string _Search = "\uE099";
        public static string Search { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Search; }
        protected static string _Delete = "\uE09A";
        public static string Delete { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Delete; }
        protected static string _Capture = "\uE09B";
        public static string Capture { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Capture; }
        protected static string _Library = "\uE09C";
        public static string Library { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Library; }
        protected static string _Database = "\uE09D";
        public static string Database { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Database; }
        protected static string _Save = "\uE09E";
        public static string Save { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Save; }
        protected static string _MapPin = "\uE09F";
        public static string MapPin { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _MapPin; }
        protected static string _Tag = "\uE0A0";
        public static string Tag { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Tag; }
        protected static string _MapDot = "\uE0A1";
        public static string MapDot { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _MapDot; }
    }
}
